
FROM registry.access.redhat.com/ubi9/go-toolset@sha256:35f08031de19eb51d6b35ed62c6357d3529bc69a8db65cf623ea5f0b44051999 as builder
ARG TARGETARCH
USER root
WORKDIR /workspace
COPY . .

# renovate: datasource=github-releases depName=pulumi/pulumi
ENV PULUMI_VERSION 3.232.0
ENV PULUMI_BASE_URL="https://github.com/pulumi/pulumi/releases/download/v${PULUMI_VERSION}/pulumi-v${PULUMI_VERSION}"
ENV PULUMI_URL="${PULUMI_BASE_URL}-linux-x64.tar.gz"

# go toolset has VERSION env with go minor version this is conflicting our version management
RUN unset VERSION \
    && GOARCH=${TARGETARCH} make build \
    && if [ "$TARGETARCH" = "arm64" ]; then export PULUMI_URL="${PULUMI_BASE_URL}-linux-arm64.tar.gz"; fi \
    && echo ${PULUMI_URL} \
    && curl -L ${PULUMI_URL} -o pulumicli.tar.gz \
    && tar -xzvf pulumicli.tar.gz 

# ubi 9.5-1732804088
FROM registry.access.redhat.com/ubi9/ubi@sha256:fd3612ebe7968002122fb8c41df2cf9bd3f9916c573f7248113cdec1d6f4c245
ARG TARGETARCH
LABEL org.opencontainers.image.authors="Redhat Developer"

COPY --from=builder /workspace/out/mapt /workspace/pulumi/pulumi /usr/local/bin/

ENV PULUMI_CONFIG_PASSPHRASE "passphrase" 

ENV AWS_SDK_LOAD_CONFIG=1 \
    ARCH_N=x86_64

# Pulumi plugins
# renovate: datasource=github-releases depName=pulumi/pulumi-aws
ARG PULUMI_AWS_VERSION=v7.27.0
# renovate: datasource=github-releases depName=pulumi/pulumi-awsx
ARG PULUMI_AWSX_VERSION=v3.5.0
# renovate: datasource=github-releases depName=pulumi/pulumi-azure-native
ARG PULUMI_AZURE_NATIVE_VERSION=v3.17.0
# renovate: datasource=github-releases depName=pulumi/pulumi-command
ARG PULUMI_COMMAND_VERSION=v1.2.1
# renovate: datasource=github-releases depName=pulumi/pulumi-tls
ARG PULUMI_TLS_VERSION=v5.3.1
# renovate: datasource=github-releases depName=pulumi/pulumi-random
ARG PULUMI_RANDOM_VERSION=v4.19.2
# renovate: datasource=github-releases depName=pulumi/pulumi-aws-native
ARG PULUMI_AWS_NATIVE_VERSION=v1.62.0
# renovate: datasource=github-releases depName=pulumi/pulumi-gitlab
ARG PULUMI_GITLAB_VERSION=v9.11.0

ENV PULUMI_HOME "/opt/mapt/run" 
WORKDIR ${PULUMI_HOME}

RUN mkdir -p /opt/mapt/run \
    && pulumi plugin install resource aws ${PULUMI_AWS_VERSION} \
    && pulumi plugin install resource azure-native ${PULUMI_AZURE_NATIVE_VERSION} \
    && pulumi plugin install resource command ${PULUMI_COMMAND_VERSION} \
    && pulumi plugin install resource tls ${PULUMI_TLS_VERSION} \
    && pulumi plugin install resource random ${PULUMI_RANDOM_VERSION} \
    && pulumi plugin install resource awsx ${PULUMI_AWSX_VERSION} \
    && pulumi plugin install resource aws-native ${PULUMI_AWS_NATIVE_VERSION} \
    && pulumi plugin install resource gitlab ${PULUMI_GITLAB_VERSION} \
    && chown -R 1001:0 /opt/mapt/run \
    && chmod -R ug+rwx /opt/mapt/run

USER 1001
ENTRYPOINT ["mapt"]
CMD ["-h"]

