
FROM docker.io/library/golang:1.19-alpine as builder 

USER root
WORKDIR /workspace
COPY . .

ENV PULUMI_VERSION 3.62.0
ENV PULUMI_URL https://github.com/pulumi/pulumi/releases/download/v${PULUMI_VERSION}/pulumi-v${PULUMI_VERSION}-linux-x64.tar.gz

RUN apk -U upgrade \
    && apk add make gcc musl-dev curl \
    && make build \
    && curl -LO ${PULUMI_URL} \
    && tar -xzvf pulumi-v${PULUMI_VERSION}-linux-x64.tar.gz

# TODO review quay build with entitlements (microdnf...)
# FROM registry.access.redhat.com/ubi8/ubi-minimal
# FROM docker.io/library/alpine:3.17
FROM mcr.microsoft.com/azure-cli:2.47.0

LABEL org.opencontainers.image.authors="Adrian Riobo<ariobolo@redhat.com>"

COPY --from=builder /workspace/out/qenvs /workspace/pulumi/pulumi /usr/local/bin/

ENV INTERNAL_OUTPUT=/tmp/qenvs \
    PULUMI_CONFIG_PASSPHRASE="passphrase" \
    AWS_SDK_LOAD_CONFIG=1

VOLUME [ "${INTERNAL_OUTPUT}" ]

RUN apk add aws-cli \
    && mkdir -p "${INTERNAL_OUTPUT}" 

ENTRYPOINT [ "qenvs" ]

