
FROM registry.access.redhat.com/ubi9/go-toolset:1.20.10-2.1699551725 as builder

USER root
WORKDIR /workspace
COPY . .

# renovate: datasource=github-releases depName=pulumi/pulumi
ENV PULUMI_VERSION 3.96.2
ENV PULUMI_URL https://github.com/pulumi/pulumi/releases/download/v${PULUMI_VERSION}/pulumi-v${PULUMI_VERSION}-linux-x64.tar.gz

RUN make build \
    && curl -L ${PULUMI_URL} -o pulumicli.tar.gz \
    && tar -xzvf pulumicli.tar.gz 

FROM registry.access.redhat.com/ubi9/ubi

LABEL org.opencontainers.image.authors="Adrian Riobo<ariobolo@redhat.com>"

COPY --from=builder /workspace/out/qenvs /workspace/pulumi/pulumi /usr/local/bin/

ENV INTERNAL_OUTPUT=/tmp/qenvs \
    PULUMI_CONFIG_PASSPHRASE="passphrase" \
    AWS_SDK_LOAD_CONFIG=1

VOLUME [ "${INTERNAL_OUTPUT}" ]

ENV AWS_CLI_VERSION 2.15.1
ENV AWS_CLI_URL https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWS_CLI_VERSION}.zip

ENV AZ_CLI_VERSION 2.55.0
ENV AZ_CLI_RPM https://packages.microsoft.com/rhel/9.0/prod/Packages/a/azure-cli-${AZ_CLI_VERSION}-1.el9.x86_64.rpm

# Pulumi plugins
# renovate: datasource=github-releases depName=pulumi/pulumi-aws
ARG PULUMI_AWS_VERSION=v6.13.3
# renovate: datasource=github-releases depName=pulumi/pulumi-aws
ARG PULUMI_AWSX_VERSION=v2.3.0
# renovate: datasource=github-releases depName=pulumi/pulumi-azure-native
ARG PULUMI_AZURE_NATIVE_VERSION=v2.21.0
# renovate: datasource=github-releases depName=pulumi/pulumi-command
ARG PULUMI_COMMAND_VERSION=v0.9.2
# renovate: datasource=github-releases depName=pulumi/pulumi-tls
ARG PULUMI_TLS_VERSION=v5.0.0
# renovate: datasource=github-releases depName=pulumi/pulumi-random
ARG PULUMI_RANDOM_VERSION=v4.15.0

RUN curl ${AWS_CLI_URL} -o awscliv2.zip \
    && dnf install -y unzip \
    && unzip awscliv2.zip \
    && ./aws/install \
    && curl -L ${AZ_CLI_RPM} -o azure-cli.rpm \
    && dnf install -y azure-cli.rpm \
    && rm -rf aws awscliv2.zip azure-cli.rpm \
    && dnf clean all \
  	&& rm -rf /var/cache/yum \
    && mkdir -p "${INTERNAL_OUTPUT}" \
    && pulumi plugin install resource aws ${PULUMI_AWS_VERSION} \
    && pulumi plugin install resource awsx ${PULUMI_AWSX_VERSION} \
    && pulumi plugin install resource azure-native ${PULUMI_AZURE_NATIVE_VERSION} \
    && pulumi plugin install resource command ${PULUMI_COMMAND_VERSION} \
    && pulumi plugin install resource tls ${PULUMI_TLS_VERSION} \
    && pulumi plugin install resource random ${PULUMI_RANDOM_VERSION}

# TODO review permissions on sharing mounting volume from host
# USER 65532:65532

ENTRYPOINT ["qenvs"]
# Default to show help
CMD ["-h"]

