FROM docker.io/hashicorp/packer:1.8.4

WORKDIR /workspace
# context is packer folder
COPY windows .

RUN apk add --update curl aws-cli jq \
    && mv oci/entrypoint.sh /usr/local/bin

ENTRYPOINT entrypoint.sh


