version: "2"

run:
  timeout: 20m
  skip-dirs:
    - vendor
    - tools/vendor
  concurrency: 1

linters:
  disable:
    - govet

linters-settings:
  govet:
    enable-all: true

issues:
  exclude-dirs:
    - vendor
    - tools/vendor
