version: 2

run:
  timeout: 20m
  skip-dirs:
    - vendor
    - tools/vendor
  skip-files:
    - pkg/provider/ibmcloud/action/powervs/powervs.go
  concurrency: 1

linters-settings:
  govet:
    enable-all: true

issues:
  exclude-dirs:
    - vendor
    - tools/vendor
