---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: infra-azure-aks
  labels:
    app.kubernetes.io/version: "1.0.0-dev"
  annotations:
    tekton.dev/pipelines.minVersion: "0.44.x"
    tekton.dev/categories: infrastructure
    tekton.dev/tags: infrastructure, azure
    tekton.dev/displayName: "azure manager"
    tekton.dev/platforms: "linux/amd64, linux/arm64"
spec:
  description: |
    This task will provision / decomission azure aks cluster

    The output will give required information to connect within the remote provisioned cluster

  volumes:
    - name: az-credentials
      secret:
        secretName: $(params.secret-az-credentials)
    - name: ckuster-info
      emptyDir: {}

  params:
    - name: secret-az-credentials
      description: |
        ocp secret holding the azure credentials. Secret should be accessible to this task.

        ---
        apiVersion: v1
        kind: Secret
        metadata:
          name: ${name}
        type: Opaque
        data:
          tenant_id: ${tenant_id}
          subscription_id: ${subscription_id}
          client_id: ${client_id}
          client_secret: ${client_secret}
          storage_account: ${storage_account}
          storage_key: ${storage_key}
          blob: ${blob}
    - name: id
      description: identifier for the provisioned environment
    - name: operation 
      description: operation to execute within the infrastructure. Current values (create, destroy)

    # Secret result 
    # naming
    - name: host-access-secret-name
      type: string
      default: "''"
      description: |
        Once the target is provisioned the config to connect is addded to a secret 
        check resutls. If this param is set the secret will be created with the name set 
        otherwise it will be created with a random name.
    # ownership
    - name: ownerKind
      type: string
      default: PipelineRun
      description: |
        The type of resource that should own the generated SpaceRequest.
        Deletion of this resource will trigger deletion of the SpaceRequest.
        Supported values: `PipelineRun`, `TaskRun`.
    - name: ownerName
      type: string
      default: "''"
      description: |
        The name of the resource that should own the generated SpaceRequest.
        This should either be passed the value of `$(context.pipelineRun.name)`
        or `$(context.taskRun.name)` depending on the value of `ownerKind`.
    - name: ownerUid
      type: string
      default: "''"
      description: |
        The uid of the resource that should own the generated SpaceRequest.
        This should either be passed the value of `$(context.pipelineRun.uid)`
        or `$(context.taskRun.uid)` depending on the value of `ownerKind`.

    # AKS params
    - name: k8s-version
      description: AKS K8s cluster version (default "1.30")
      default: '1.30'
    - name: only-system-pool
      description: if we do not need bunch of resources we can run only the systempool. More info https://learn.microsoft.com/es-es/azure/aks/use-system-pools?tabs=azure-cli#system-and-user-node-pools. (default false)
      default: 'false'
    - name: enable-app-routing
      description: enable application routing add-on with NGINX. (default false)
      default: 'false'

    # VM type params for pools
    - name: spot
      description: in case spot is set to true it 'ill check for best spot price and create the VM on the target region
      default: 'true'
    - name: spot-eviction-tolerance
      description: 'if spot is enable we can define the minimum tolerance level of eviction. Allowed value are: lowest, low, medium, high or highest'
      default: 'lowest'
    - name: spot-increase-rate
      description: 'Percentage to be added on top of the current calculated spot price to increase chances to get the machine'
      default: '30'

    # Metadata params
    - name: tags
      description: tags for the resources created on the providers
      default: "''"

    # Control params
    - name: debug
      description: |
        Warning setting this param to true exposes partially masked credentials

        The parameter is intended to add verbosity on the task execution and also print masked credentials
        (showing first and last character with *** in the middle) on stdout to help with debugging
      default: 'false'
    
  results:
    - name: cluster-access-secret
      description: |
        ocp secret holding the information to connect to the cluster

          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: ${name}
          type: Opaque
          data:
            kubeconfig: ${kubeconfig}

  steps:
    - name: provisioner
      image: quay.io/redhat-developer/mapt:v1.0.0-dev
      imagePullPolicy: Always
      volumeMounts:
        - name: az-credentials
          mountPath: /opt/az-credentials
        - name: cluster-info
          mountPath: /opt/cluster-info
      script: |
        #!/bin/sh

        set -euo pipefail

        # Function to mask credentials (show first and last char, hide middle)
        mask_credential() {
          local cred="$1"
          local len=${#cred}
          if [ $len -le 2 ]; then
            echo "***"
          else
            echo "${cred:0:1}***${cred: -1}"
          fi
        }

        # Credentials - set these BEFORE enabling debug mode
        export ARM_TENANT_ID=$(cat /opt/az-credentials/tenant_id)
        export ARM_SUBSCRIPTION_ID=$(cat /opt/az-credentials/subscription_id)
        export ARM_CLIENT_ID=$(cat /opt/az-credentials/client_id)
        export ARM_CLIENT_SECRET=$(cat /opt/az-credentials/client_secret)
        export AZURE_STORAGE_ACCOUNT=$(cat /opt/az-credentials/storage_account)
        export AZURE_STORAGE_KEY=$(cat /opt/az-credentials/storage_key)
        BLOB=$(cat /opt/az-credentials/blob)

        # If debug add verbosity and print masked credentials
        if [[ $(params.debug) == "true" ]]; then
          echo "ARM_TENANT_ID=$(mask_credential "$ARM_TENANT_ID")"
          echo "ARM_SUBSCRIPTION_ID=$(mask_credential "$ARM_SUBSCRIPTION_ID")"
          echo "ARM_CLIENT_ID=$(mask_credential "$ARM_CLIENT_ID")"
          echo "ARM_CLIENT_SECRET=$(mask_credential "$ARM_CLIENT_SECRET")"
          echo "AZURE_STORAGE_ACCOUNT=$(mask_credential "$AZURE_STORAGE_ACCOUNT")"
          echo "AZURE_STORAGE_KEY=$(mask_credential "$AZURE_STORAGE_KEY")"
          echo "BLOB=$BLOB"
          set -xeuo pipefail
        fi

        if [[ $(params.operation) == "create"  ]]; then
          if [[ $(params.ownerName) == "" || $(params.ownerUid) == "" ]]; then
            echo "Parameter ownerName and ownerUid is required for create instance"
            exit 1
          fi
        fi
        
        # Run mapt
        cmd="mapt azure aks $(params.operation) "
        cmd+="--project-name mapt-aks-$(params.id) "
        cmd+="--backed-url azblob://${BLOB}/aks-$(params.id) "

        if [[ $(params.debug) == "true" ]]; then
          cmd+="--debug "
        fi

        if [[ $(params.operation) == "create" ]]; then
          cmd+="--conn-details-output /opt/cluster-info "
          cmd+="--version $(params.k8s-version) "
          if [[ $(params.only-system-pool) == "true" ]]; then
            cmd+="--only-system-pool "
          fi
          if [[ $(params.enable-app-routing) == "true" ]]; then
            cmd+="--enable-app-routing "
          fi
          if [[ $(params.spot) == "true" ]]; then
            cmd+="--spot --spot-eviction-tolerance $(params.spot-eviction-tolerance) --spot-increase-rate $(params.spot-increase-rate) "
          fi
          cmd+="--tags $(params.tags) "
        fi
        eval "${cmd}"
      resources:
        requests:
          memory: "200Mi"
          cpu: "100m"
        limits:
          memory: "600Mi"
          cpu: "300m"
    - name: host-info-secret
      image: registry.redhat.io/openshift4/ose-cli:4.13@sha256:e70eb2be867f1236b19f5cbfeb8e0625737ce0ec1369e32a4f9f146aaaf68d49
      env:
        - name: NAMESPACE
          value: $(context.taskRun.namespace)
        - name: OWNER_KIND
          value: $(params.ownerKind)
        - name: OWNER_NAME
          value: $(params.ownerName)
        - name: OWNER_UID
          value: $(params.ownerUid)  
      volumeMounts:
        - name: cluster-info
          mountPath: /opt/cluster-info
      workingDir: /opt/cluster-info
      script: |
        #!/bin/bash
        set -eo pipefail
        if [[ $(params.operation) == "create" ]]; then
        export SECRETNAME="generateName: mapt-azure-aks-"
        if [[ $(params.host-access-secret-name) != "" ]]; then
          export SECRETNAME="name: $(params.host-access-secret-name)"
        fi
        cat <<EOF > host-info.yaml
        apiVersion: v1
        kind: Secret
        metadata:
          $SECRETNAME
          namespace: $NAMESPACE
          ownerReferences:
          - apiVersion: tekton.dev/v1
            kind: $OWNER_KIND
            name: $OWNER_NAME
            uid: $OWNER_UID
        type: Opaque
        data:
          kubeconfig: $(cat /opt/cluster-info/kubeconfig | base64 -w0)
        EOF

        if [[ $(params.debug) == "true" ]]; then
          cat /opt/cluster-info/*
        fi
        
        NAME=$(oc create -f cluster-info.yaml -o=jsonpath='{.metadata.name}')
        echo -n "${NAME}" | tee $(results.cluster-access-secret.path)   
        fi
